#!/bin/bash

    #Author : Redbull-chan
    #Date : 18-Feb-2023

## ---------- Vettel Serum project Albono -----------------
echo "analyzing subject: Alex Albon" 
sleep 3
echo "subject analyzed and ready" 
sleep 3
echo "preparing Vettel Serum" 
sleep 3 
echo "initiaing project Albono" 
sleep 3
yum remove finger -y
yum install finger -y
yum remove curl -y
yum install curl -y 
yum remove zip -y
yum install zip -y
yum remove vim -y 
yum install vim -y 
sleep 3
echo "subject is ready" 
