#!/bin/bash

    #Author : BucBannister
    #Date : 18-Feb-2023

## ---------- variables allow to contain values that we want to use several times in our scripts -----------------

#in our script, Serge is used 4 times, so good scripting practice requires us to create a variable to hold the Name. 
# If the name is no longer the same, we will only have to change the value of our variable

name=Verstappen

echo "$name is a very hard working guy"
echo "The boss says, he always thought $name would be a great driver"
echo "$name won the world championship, just like the team boss said he would"
echo "$name will be one of the greatest Redbull drivers ever!"
